import type { ModuleDefinition } from "@/types";

export const modules: ModuleDefinition[] = [
  {
    id: "qr-checkins",
    name: "Access & Attendance",
    description: "Reusable QR access points for attendance, visitors, forms, members, and assets.",
    category: "Operations",
    status: "enabled",
    icon: "qr",
    href: "/dashboard/qr",
  },
  {
    id: "members",
    name: "Members",
    description: "Manage member profiles, roles, invitations, and organization access.",
    category: "Engagement",
    status: "enabled",
    icon: "members",
    href: "/dashboard/members",
  },
  {
    id: "inventory",
    name: "Inventory",
    description: "Track assets, equipment, kits, tools, keys, and assigned inventory across locations.",
    category: "Operations",
    status: "enabled",
    icon: "inventory",
    href: "/dashboard/inventory",
  },
  {
    id: "forms",
    name: "Forms",
    description: "Collect structured requests, surveys, applications, and feedback.",
    category: "Workspace",
    status: "enabled",
    icon: "forms",
    href: "/dashboard/forms",
  },
  {
    id: "bookings",
    name: "Bookings",
    description: "Coordinate reservations, rooms, services, appointments, and events.",
    category: "Engagement",
    status: "disabled",
    icon: "bookings",
  },
  {
    id: "tasks",
    name: "Tasks",
    description: "Assign operational work, track ownership, and standardize follow-up.",
    category: "Operations",
    status: "disabled",
    icon: "tasks",
  },
  {
    id: "lunch-system",
    name: "Lunch System",
    description: "Coordinate meal planning, lunch signups, preferences, and counts.",
    category: "Facilities",
    status: "disabled",
    icon: "lunch",
  },
  {
    id: "visitors",
    name: "Visitors",
    description: "Register guests, front desk arrivals, badges, and host notifications.",
    category: "Facilities",
    status: "disabled",
    icon: "visitors",
  },
  {
    id: "equipment",
    name: "Equipment",
    description: "Reserve, assign, and inspect shared equipment across teams.",
    category: "Facilities",
    status: "disabled",
    icon: "equipment",
  },
];
