import {
  Activity,
  Building2,
  ClipboardList,
  CreditCard,
  LayoutDashboard,
  Puzzle,
  QrCode,
  Settings,
  UsersRound,
  Package,
  FileArchive,
  Receipt,
  AlertCircle,
  CalendarDays,
  CheckSquare,
  KeyRound,
  UserCheck,
  CalendarRange,
} from "lucide-react";
import type { DashboardNavItem } from "@/types";

export const dashboardNavItems: DashboardNavItem[] = [
  { title: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  { title: "Access & Attendance", href: "/dashboard/qr", icon: QrCode },
  { title: "Forms", href: "/dashboard/forms", icon: ClipboardList },
  { title: "Members", href: "/dashboard/members", icon: UsersRound },
  { title: "Inventory", href: "/dashboard/inventory", icon: Package },
  { title: "Documents", href: "/dashboard/documents", icon: FileArchive },
  { title: "Receipts", href: "/dashboard/receipts", icon: Receipt },
  { title: "Issue Management", href: "/dashboard/issues", icon: AlertCircle },
  { title: "Fault Reports", href: "/dashboard/fault-reports", icon: ClipboardList },
  { title: "Bookings", href: "/dashboard/bookings", icon: CalendarDays },
  { title: "Key Management", href: "/dashboard/keys", icon: KeyRound },
  { title: "Checklists", href: "/dashboard/checklists", icon: CheckSquare },
  { title: "Visitors", href: "/dashboard/visitors", icon: UserCheck },
  { title: "Annual Planner", href: "/dashboard/annual-planner", icon: CalendarRange },
  { title: "Modules", href: "/dashboard/modules", icon: Puzzle },
  { title: "Organizations", href: "/dashboard/organizations", icon: Building2 },
  { title: "Settings", href: "/dashboard/settings", icon: Settings },
  { title: "Billing", href: "/dashboard/billing", icon: CreditCard },
  { title: "Audit Logs", href: "/dashboard/audit-logs", icon: Activity },
];
